# Generated by Django 5.0 on 2024-05-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='treatment',
            field=models.ManyToManyField(to='api.drug'),
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up',
            field=models.ManyToManyField(to='api.followup'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.history'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='microbio_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.microbioexam'),
        ),
        migrations.AddField(
            model_name='microbioexam',
            name='tests',
            field=models.ManyToManyField(to='api.microbiotests'),
        ),
        migrations.AddField(
            model_name='pasttreatments',
            name='medications',
            field=models.ManyToManyField(to='api.drug'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='past_treatments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pasttreatments'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='workup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workupexam'),
        ),
        migrations.AddField(
            model_name='workupexam',
            name='tests',
            field=models.ManyToManyField(to='api.workuptest'),
        ),
    ]
