# Generated by Django 5.0 on 2024-05-26 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='latest_Visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 10, 44, 243700, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
