# Generated by Django 5.0 on 2024-05-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_latest_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='latest_Visit',
            new_name='latest_visit',
        ),
    ]
