version: '3.9'
services:

  diagnosis_record_db: 
    # UPON DEPLOYMENT: restart: always
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: "localhost"
    expose:
      - 5433
    ports:
      - 5433:5432 
    volumes:
      - diagnosis_record_db:/var/lib/postgresql/data

volumes:
  diagnosis_record_db:


